### ISSUE TITLE
smirik quiz bundle 

### ISSUE THREAD

**Issue by RihabOueslati** [hantsy/angularjs-cakephp-sample#10]
Problem 1
    - The requested package smirik/quiz-bundle could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see

**Comment by hantsy** [comment]
According to the composer.json, only requires CakePHP:

```
     "require": {
        "cakephp/cakephp": "2.6.*"
     }
```

**Comment by hantsy** [comment]
not a bug, close
