### ISSUE TITLE
Enabling HTML5 History

### ISSUE THREAD

**Issue by iamdriz** [hantsy/angularjs-cakephp-sample#3]
No longer an issue.

**Comment by hantsy** [comment]
This purpose of this sample is demonstrating basic AngularJS and REST API. You can read the oficial AngularJS document and enable html5Mode according, it is not complex.

**Comment by hantsy** [comment]
@iamdriz This project is not added new codes for a long time. If you are interested in the latest AngularJS 1.5+, check https://github.com/hantsy/angular-es6-sample, it is more robust and I used it as base codes for several projects.
