### ISSUE TITLE
error when vagrant up

### ISSUE THREAD

**Issue by agarzon** [hantsy/angularjs-cakephp-sample#4]
There are errors in the configuration of this machine. Please fix
the following errors and try again:

```shell
==> default: Successfully added box 'precise64' (v0) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'berkshelf'.
```

**Comment by justinmoh** [comment]
@hantsy I'm getting this error as well and I've no clue how to deal with it. Kindly assist. Thank you.

**Comment by hantsy** [comment]
@justinmoh ， @agarzon  The Vargrant configuration file is contributed by community. I have not tried when I was coding this sample. Maybe I will fix this problem in future, currently I am a newbie of Vargrant.
Of course, any contribution is welcome.

**Comment by chrisvogt** [comment]
@justinmoh @agarzon I saw the same error until installing the [vagrant berkshelf](https://github.com/berkshelf/vagrant-berkshelf) plugin:

```sh
   vagrant plugin install vagrant-berkshelf
```

**Comment by hantsy** [comment]
@chrisvogt  Can you send a pull request if you resolved this problem? I appreciate your help.
 I am not a professional of Vagrant.
