### ISSUE TITLE
lost auth data when refresh

### ISSUE THREAD

**Issue by nevoeiro** [hantsy/angularjs-cakephp-sample#6]
Hi @hantsy 

Thanks for the sample. I started using cakephp and I'm trying to build a prototype for a client using angularjs.
I follow your tutorial steps and I have a problem in authentication part. I can register and login with my user but if I refresh my page, I lost the auth data. Can you help?

thanks

**Comment by hantsy** [comment]
@nevoeiro Yeah, this is a problem. The client UI is a SPA application, I stored the authentication info in $rootScope, it will lost after refresh. 

If you need this feature, try to store your auth in cookie or localStorge, and load them into $rootScope at app startup stage.

**Comment by hantsy** [comment]
@nevoeiro This project is not added new codes for a long time. If you are interested in the latest AngularJS 1.5+, check https://github.com/hantsy/angular-es6-sample, it is more robust and I used it as base codes for several projects. I think it includes what you want there.
