### ISSUE TITLE
app/index routing

### ISSUE THREAD

**Issue by spacebiscuit** [hantsy/angularjs-cakephp-sample#7]
Thanks for a fantastic wiki - just what I have been looking for.

One I run the app/index I get:

Error: The action index is not defined in controller AppController

Do i need to set something up in the routes to handle this. I've gone over the instructions a few times and can't see what I'm missing.

Tank you in advance.

**Comment by hantsy** [comment]
AppController is a hook class in CakePHP 2, as the base class for all Controller classes, can not be accessed directly.

If you want to know the route rules,I usually used default rules, there is a [Config/routes.php](https://github.com/hantsy/angularjs-cakephp-sample/blob/master/Config/routes.php).

All REST APIs, such as **/posts** can be tested by client tools, such as  PostMan(chrome plugin).

**Comment by spacebiscuit** [comment]
Hi Hantsy - sure I understand that the App controller is the key fundamental controller in Cake2 but I can't see how your example routes for the test cases so that the App controller is not called.

In your routes example I only see that it handles 'posts' and 'users'?

**Comment by hantsy** [comment]
If you used Cake2 before , you have to know `AppController` only includes some common codes, such as security control for all controllers, does not contains the action method for routes.

If you needs a default `index` routes for the application, create a Controller yourself, then replace current `PagesController` routes with urs.

**Comment by spacebiscuit** [comment]
Routing relies on an controller and action, how can I route to a non-standard cake url within the webroot? Are you sure this is possible?

### EDIT

I managed to get it to work by creating a distinct domain to run the Angular on to keep it separated from the Cake app.

Maybe the wiki can be updated to make it clear that the front end and RESTful API should be on their own domains because the file structure example in the wiki implies that it runs on a single domain.

Now to really play with this :)

**Comment by hantsy** [comment]
Yes, the frontend is designed for SPA , but not run in a standalone server. There are some other examples in my Github.com are providing separate structure for frontend and backend RESTful API.

You can follow the _gulp_ in the **angularjs-springmvc-sample-boot** to add NodeJS build system for the frontend.
