### ISSUE TITLE
Users Controller Missing View

### ISSUE THREAD

**Issue by spacebiscuit** [hantsy/angularjs-cakephp-sample#8]
When I call the Users/login method of the API I get an error on my network tab:

Error: The view for UsersController::login() was not found.
Confirm you have created the file: Users/json/login.ctp in one of the following paths:.....

This error is not reported when I call the methods of the Posts controller (index,add). I cannot see any differences, I can stop the error using:

$this->autoRender=false;

Why is the error only reported for methods of the Users controller?

**Comment by hantsy** [comment]
Please read the Routing info in the _Config/routes.php_. If you do not understand the **mapResource** and **parseExtensions** there, please read the official CakePHP manual about Resources config and view rendering.

https://github.com/hantsy/angularjs-cakephp-sample/blob/master/Config/routes.php 

http://book.cakephp.org/2.0/en/development/routing.html

http://book.cakephp.org/2.0/en/views/json-and-xml-views.html

**Comment by hantsy** [comment]
It is not a bug.

**Comment by spacebiscuit** [comment]
HI Hantsy - I am using your routes file and still I get missing view. 

Please test and you will see this anomaly.
