### ISSUE TITLE
Need Database File

### ISSUE THREAD

**Issue by manimurugank** [hantsy/angularjs-cakephp-sample#9]
Need Database File. Where can i get Database file

**Comment by hantsy** [comment]
@manimurugank Please read the [Wiki pages](https://github.com/hantsy/angularjs-cakephp-sample/wiki) to build it yourself. 

The database schema scripts is described in the second wiki pages.

[https://github.com/hantsy/angularjs-cakephp-sample/wiki/2-rest-api](https://github.com/hantsy/angularjs-cakephp-sample/wiki/2-rest-api)
